name: Build and test Go
on:
  push:
    paths:
      - '.github/workflows/ci-go.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'
      - 'command/**'
      - 'keepachangelog/**'
      - 'markdown/**'
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/ci-go.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'
      - 'command/**'
      - 'keepachangelog/**'
      - 'markdown/**'
  workflow_dispatch:

jobs:
  build-go:
    strategy:
      fail-fast: true
      matrix:
        goos: [ "linux", "darwin", "windows", "freebsd" ]
        goarch: [ "amd64", "386", "arm", "arm64" ]
        exclude:
          - goos: "darwin"
            goarch: "386"
          - goos: "darwin"
            goarch: "arm"
          - goos: "windows"
            goarch: "arm"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build .

  test-go:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - uses: robherley/go-test-action@v1
        with:
          omit: |
            pie
            untested
